name: FunSearchFlow
description: "A flow implementing FunSearch Asynchronous Search"
enable_cache: false

### Subflows specification
subflows_config:
  SamplerFlow:
    enable_cache: false
    _target_: aiflows.base_flows.AtomicFlow.instantiate_from_default_config
    name: "Proxy of the controller"
    description: "A flow that proxies The Controller."
    colink_info:
      cl:
        jwt: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwcml2aWxlZ2UiOiJ1c2VyIiwidXNlcl9pZCI6IjAyMzI4ZjY5YjA4YTE0NThmZDg2ZDk0YTA2OTIwZjc4ZDVhMWYwODZhZWY1YjllMDU0NzNiMDliZjA0NzlkMDE1OSIsImV4cCI6MTcxMDE2NTA3MX0.6tMBaehfE4rSapgYbqJQG7O0JXLul1VpDVux5Rzd3XM
        coreaddr: "http://127.0.0.1:2021"
      remote_participant_id: 02328f69b08a1458fd86d94a06920f78d5a1f086aef5b9e05473b09bf0479d0159 #id here
      remote_participant_flow_queue: SamplerFlowInputQueue #queue name here
      wait_for_response: False
      response_queue_name: FunSearchInputQueue
    backend:
      api_infos: ???
  EvaluatorFlow:
    enable_cache: false
    _target_: aiflows.base_flows.AtomicFlow.instantiate_from_default_config
    name: "Proxy of the executor"
    description: "A flow that proxies The Executor."
    colink_info:
      cl:
        jwt: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwcml2aWxlZ2UiOiJ1c2VyIiwidXNlcl9pZCI6IjAyMzI4ZjY5YjA4YTE0NThmZDg2ZDk0YTA2OTIwZjc4ZDVhMWYwODZhZWY1YjllMDU0NzNiMDliZjA0NzlkMDE1OSIsImV4cCI6MTcxMDE2NTA3MX0.6tMBaehfE4rSapgYbqJQG7O0JXLul1VpDVux5Rzd3XM
        coreaddr: "http://127.0.0.1:2021"
      remote_participant_id: 02328f69b08a1458fd86d94a06920f78d5a1f086aef5b9e05473b09bf0479d0159 #id here
      remote_participant_flow_queue: EvaluatorInputQueue #queue name here
      wait_for_response: False
      response_queue_name: FunSearchInputQueue
    py_file: ???
    function_to_run_name: ???
    test_inputs: ???
  ProgramDBFlow:
    enable_cache: false
    _target_: aiflows.base_flows.AtomicFlow.instantiate_from_default_config
    name: "Proxy of the executor"
    description: "A flow that proxies The Executor."
    colink_info:
      cl:
        jwt: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwcml2aWxlZ2UiOiJ1c2VyIiwidXNlcl9pZCI6IjAyMzI4ZjY5YjA4YTE0NThmZDg2ZDk0YTA2OTIwZjc4ZDVhMWYwODZhZWY1YjllMDU0NzNiMDliZjA0NzlkMDE1OSIsImV4cCI6MTcxMDE2NTA3MX0.6tMBaehfE4rSapgYbqJQG7O0JXLul1VpDVux5Rzd3XM
        coreaddr: "http://127.0.0.1:2021"
      remote_participant_id: 02328f69b08a1458fd86d94a06920f78d5a1f086aef5b9e05473b09bf0479d0159 #id here
      remote_participant_flow_queue: ProgramDBInputQueue #queue name here
      wait_for_response: False
      response_queue_name: FunSearchInputQueue
    evaluate_function: ???
    evaluate_file_full_content: ???