# This is an abstract flow, therefore some required fields are not defined (and must be defined by the concrete flow)
enable_cache: True

model_name: "gpt-4"
generation_parameters:
  n: 1
  max_tokens: 2000
  temperature: 0.3

  model_kwargs:
    top_p: 0.2
    frequency_penalty: 0
    presence_penalty: 0

n_api_retries: 6
wait_time_between_retries: 20

system_name: system
user_name: user
assistant_name: assistant

system_message_prompt_template:
  _target_: langchain.PromptTemplate
  template_format: jinja2

init_human_message_prompt_template:
  _target_: langchain.PromptTemplate
  template_format: jinja2

human_message_prompt_template:
  _target_: langchain.PromptTemplate
  template: "{{query}}"
  input_variables:
    - "query"
  template_format: jinja2
input_interface_initialized:
  - "query"

query_message_prompt_template:
  _target_: langchain.PromptTemplate
  template_format: jinja2

demonstrations: null
demonstrations_response_template: null

output_interface:
  - "api_output"
