name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Describe the bug you're seeing. A clear and concise description of what the bug is.
      placeholder: |
       Description of the bug
       
       Steps to reproduce bug
       
       Expected behavior and actual behavior

       Extra information (library version, etc.)
    validations:
      required: true
  - type: markdown
      attributes:
        value: |
          Optional information, please fill out if you can as it will help us fix the bug faster.
  - type: textarea
    id: bug-reproduce
    attributes:
      label: Describe how to reproduce the bug
      description: |
        Please provide a minimal code example that reproduces the bug.
      placeholder: |
        ```python
        # Minimal code example
        ```
      validations:
        required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs and error messages
      description: |
        Please provide any logs or error messages you are seeing.
      placeholder: |
        ```
        # logs and error, messages, full traceback
        ```
      validations:
        required: false
  - type: textarea
    id: extra-info
    attributes:
      label: Extra information
      description: Any other information you think might be helpful.
      paceholder: extra information here
      validations:
        required: false