name: Report a bug
description: File a bug report
labels: ["needs triage", "bug"]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    attributes:
      label: Bug Description
      description: Describe the bug you're seeing. A clear and concise description of what the bug is.
      placeholder: |
        Description of the bug
       
        Steps to reproduce bug
        
        Expected behavior and actual behavior

        Extra information (library version, etc.)

    validations:
      required: true

  - type: markdown
    attributes:
      value: "Optional information, please fill out if you can as it will help us fix the bug faster."

  - type: textarea
    attributes:
      label: Describe how to reproduce the bug (optional)
      description: Please provide a minimal code example that reproduces the bug.
      placeholder: |
        ```python
         Minimal code example
        ```
      render: python
    validations:
      required: false

  - type: textarea
    attributes:
      label: Logs and error messages (optional)
      description: Please provide any logs or error messages you are seeing.
      placeholder: "Copy and paste logs"
      value: |
        ```
         Error messages and logs here please
        ```
    validations:
      required: false

  - type: textarea
    attributes:
      label: Extra information (optional)
      description: Any other information you think might be helpful.
      paceholder: "extra information here"
    validations:
      required: false