
flow:  # Overrides the for the flow config
  # input and output interfaces of SequentialFlow
  input_interface:
    - "artifact"

  output_interface:
    - "artifact"


  name: TestFlow
  
  _target_: aiflows.base_flows.CircularFlow.instantiate_from_default_config
  max_rounds: 30
  subflows_config:
    ProgramDBFlow:
      _target_: flow_modules.aiflows.ProgramDBFlowModule.ProgramDBFlow.instantiate_from_default_config
      artifact_to_evolve_name: priority_function 
      evaluate_function_name: evaluate
      evaluate_function_file_path: functions.py
      artifacts_per_prompt: 2
    EvaluatorFlow:
      _target_: flow_modules.aiflows.EvaluatorFlowModule.EvaluatorFlow.instantiate_from_default_config
      test_inputs: 
        test_1: 
          n: 3
        test_2:
          n: 4
        test_3:
          n: 5
        test_4:
          n: 6
        test_5:
          n: 7
        test_6:
          n: 8


    SamplerFlow:
      _target_: flow_modules.aiflows.SamplerFlowModule.SamplerFlow.instantiate_from_default_config
      system_message_prompt_template:
        partial_variables:
          evaluate_name: ${flow.subflows_config.ProgramDBFlow.evaluate_function_name}
          evolve_name: ${flow.subflows_config.ProgramDBFlow.artifact_to_evolve_name}
          artifacts_per_prompt: ${flow.subflows_config.ProgramDBFlow.artifacts_per_prompt}
      backend:
        api_infos: ???
     
  topology:
    #fist flow to execute
    - goal: Evaluate Code
      input_interface:
        _target_: aiflows.interfaces.KeyInterface
      flow: EvaluatorFlow
      reset: false
    - goal: Register Program
      input_interface:
        _target_: aiflows.interfaces.KeyInterface
        keys_to_set:
          operation: "register_program"
      flow: ProgramDBFlow
      output_interface:
        _target_: aiflows.interfaces.KeyInterface
        keys_to_select: ["retrieved"]
      reset: false
    - goal: Extract Prompt
      input_interface:
        _target_: aiflows.interfaces.KeyInterface
        keys_to_set:
          operation: "get_prompt"
        keys_to_select: ["operation"]
      output_interface:
        _target_: aiflows.interfaces.KeyInterface
        keys_to_rename:
          retrieved.evaluate_file_full_content: header
          retrieved.code: code
          retrieved.version_generated : version_generated
          retrieved.island_id: island_id
      flow: ProgramDBFlow
      reset: false
    - goal: Query LLM
      input_interface:
        _target_: aiflows.interfaces.KeyInterface
        keys_to_select: ["header","code","island_id"]
      flow: SamplerFlow
      output_interface:
        _target_: aiflows.interfaces.KeyInterface
        keys_to_rename:
          api_output: artifact
        keys_to_select: ["artifact","island_id"]
        
     