name: "ReverseNumberTwice"
description: "A sequential flow that reverses a number twice."
_target_: ReverseNumberFlowModule.ReverseNumberSequentialFlow.instantiate_from_default_config

# input and output interfaces of SequentialFlow
input_interface:
  - "number"

output_interface:
  - "output_number"

#configuration of subflows
subflows_config:
  first_reverse_flow:
    _target_: aiflows.base_flows.AtomicFlow.instantiate_from_default_config
    user_id: local
    flow_type: ReverseNumberAtomicFlow_served
    name: "ReverseNumberFirst"
    description: "A flow that takes in a number and reverses it."
  second_reverse_flow:
    _target_: aiflows.base_flows.AtomicFlow.instantiate_from_default_config
    user_id: local
    flow_type: ReverseNumberAtomicFlow_served
    name: "ReverseNumberSecond"
    description: "A flow that takes in a number and reverses it AGAIN."
    config_overrides:
      description: "Overriden description."
