name: "ReverseNumberTwice"
description: "A sequential flow that reverses a number twice."
_target_: ReverseNumberFlowModule.ReverseNumberSequentialFlow.instantiate_from_default_config
flow_type: ReverseNumberSequentialFlow_served_20
colink_info:
  cl:
    jwt: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwcml2aWxlZ2UiOiJ1c2VyIiwidXNlcl9pZCI6IjAyNjk3ZGFjOGE5NGM1ZGQwNWIyYjRmNjM2MzBlOWU0NWJmOTA2MzZkMDBkYTlkZDFhMmFlZTY3YTA1MjZkNmJkMSIsImV4cCI6MTcxMTYzMjUxM30.yEQmx0rdOvVY23H1JCcH_iMXwWfqMKXw2FgUK0FwYYQ
    coreaddr: "http://127.0.0.1:2021"
# input and output interfaces of SequentialFlow
input_interface:
  - "number"

output_interface:
  - "output_number"

#configuration of subflows
subflows_config:
  first_reverse_flow:
    _target_: aiflows.base_flows.AtomicFlow.instantiate_from_default_config
    user_id: local
    flow_type: ReverseNumberAtomicFlow_served_20
    name: "ReverseNumberFirst"
    description: "A flow that takes in a number and reverses it."
  second_reverse_flow:
    _target_: aiflows.base_flows.AtomicFlow.instantiate_from_default_config
    user_id: local
    flow_type: ReverseNumberAtomicFlow_served_20
    name: "ReverseNumberSecond"
    description: "A flow that takes in a number and reverses it AGAIN."
    config_overrides:
      description: "Overriden description."
