name: "ReverseNumberTwice"
description: "A sequential flow that reverses a number twice."

input_interface:
  - "number"

output_interface:
  - "output_number"

subflows_config:
  first_reverse_flow:
    _target_: reverse_number_atomic.ReverseNumberAtomicFlow.instantiate_from_default_config
    name: "ReverseNumberFirst"
    description: "A flow that takes in a number and reverses it."
  second_reverse_flow:
    _target_: reverse_number_atomic.ReverseNumberAtomicFlow.instantiate_from_default_config
    name: "ReverseNumberSecond"
    description: "A flow that takes in a number and reverses it."

topology:
  - goal: reverse the input number
    # circular flow as the orchestrator, prepare the correct input for the agent
    input_interface:
      _target_: flows.interfaces.KeyInterface
      keys_to_select: ["number"]
    flow: first_reverse_flow
    output_interface:
      _target_: flows.interfaces.KeyInterface
      keys_to_rename:
        output_number: first_reverse_output
      keys_to_select: ["first_reverse_output"]
    reset: false

  - goal: reverse the output of the first reverse
    # circular flow as the orchestrator, prepare the correct input for the agent
    input_interface:
      _target_: flows.interfaces.KeyInterface
      keys_to_rename:
        first_reverse_output: number
      keys_to_select: ["number"]
    flow: second_reverse_flow
    output_interface:
      _target_: flows.interfaces.KeyInterface
      keys_to_select: ["output_number"]
    reset: false
