name: "ReverseNumber"
description: "A flow that takes in a number and reverses it."

input_interface:
  _target_: flows.interfaces.KeyInterface
  keys_to_select: ["number"]

output_interface: # Connector between the Flow's output and the caller
  _target_: flows.interfaces.KeyInterface
  keys_to_rename:
    output_number: "reversed_number" # Rename the api_output to answer
