name: "ReverseNumberTwice"
description: "A sequential flow that reverses a number twice."
_target_: ReverseNumberFlowModule.ReverseNumberSequentialFlow.instantiate_from_default_config

# input and output interfaces of SequentialFlow
input_interface:
  - "number"

output_interface:
  - "output_number"

#configuration of subflows
subflows_config:
  first_reverse_flow:
    user_id: ???
    flow_endpoint: reverse_number_atomic
    name: "ReverseNumberFirst"
    description: "A flow that takes in a number and reverses it."
  second_reverse_flow:
    user_id: ???
    flow_endpoint: reverse_number_atomic
    name: "ReverseNumberSecond"
    description: "A flow that takes in a number and reverses it AGAIN."
