
_target_: flow_modules.aiflows.ControllerExecutorFlowModule.ControllerExecutorFlow.instantiate_from_default_config

name: "CircularFlowDemo"
description: "demo of ControllerExecutorFlowModule via Proxy"
max_rounds: 30
enable_cache: false

input_interface:
  - "goal"

output_interface:
  - "answer"
  - "status"

### Subflows specification
subflows_config:
  Controller:
    enable_cache: false
    _target_: aiflows.base_flows.AtomicFlow.instantiate_from_default_config
    name: "Proxy of the controller"
    description: "A flow that proxies The Controller."
    colink_info:
      cl:
        jwt: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwcml2aWxlZ2UiOiJ1c2VyIiwidXNlcl9pZCI6IjAzZjczZmJjNTgzOTQ5MWVlZTAzNTc4ZGFmZjBjYzM0ZjY2ODM2MDFhYWUzY2M1N2Y0YWQyMjJmYzJmYzgzM2ZmMyIsImV4cCI6MTcxMDA5MDEwN30.blBIkt4V9T10sXYHH6r1nDE8sn1Azf4Xr3QMnTqtWmo


        coreaddr: "http://127.0.0.1:2021"
      remote_participant_id: 03f73fbc5839491eee03578daff0cc34f6683601aae3cc57f4ad222fc2fc833ff3 #id here
      remote_participant_flow_queue: RemoteFlow:ControllerFlow:input_queue:1 #queue name here

  Executor:
    enable_cache: false
    _target_: aiflows.base_flows.AtomicFlow.instantiate_from_default_config
    name: "Proxy of the executor"
    description: "A flow that proxies The Executor."
    colink_info:
      cl:
        jwt: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwcml2aWxlZ2UiOiJ1c2VyIiwidXNlcl9pZCI6IjAzZjczZmJjNTgzOTQ5MWVlZTAzNTc4ZGFmZjBjYzM0ZjY2ODM2MDFhYWUzY2M1N2Y0YWQyMjJmYzJmYzgzM2ZmMyIsImV4cCI6MTcxMDA5MDEwN30.blBIkt4V9T10sXYHH6r1nDE8sn1Azf4Xr3QMnTqtWmo


        coreaddr: "http://127.0.0.1:2021"
      remote_participant_id: 03f73fbc5839491eee03578daff0cc34f6683601aae3cc57f4ad222fc2fc833ff3 #id here
      remote_participant_flow_queue: RemoteFlow:ExecutorFlow:input_queue:1 #queue name here


topology:
  - goal: "Select the next action and prepare the input for the executor."
    input_interface:
      _target_: aiflows.interfaces.KeyInterface
    flow: Controller
    output_interface:
      _target_: ControllerExecutorFlow.detect_finish_or_continue
    reset: false

  - goal: "Execute the action specified by the Controller."
    input_interface:
      _target_: aiflows.interfaces.KeyInterface
      keys_to_rename:
        command: branch
        command_args: branch_input_data
      keys_to_select: ["branch", "branch_input_data"]
    flow: Executor
    output_interface:
      _target_: aiflows.interfaces.KeyInterface
      keys_to_rename:
        branch_output_data: observation
      keys_to_select: ["observation"]
    reset: false