_target_: aiflows.base_flows.Flow.instantiate_from_default_config
name: "ProxyofChatFlowModule"
description: "A flow that proxies a remote flow."
colink_info:
    cl:
        _target_: colink.CoLink
        jwt: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwcml2aWxlZ2UiOiJ1c2VyIiwidXNlcl9pZCI6IjAyOGIwNDE5MzY4NGEzYjUzNmQ0ZDFhNTYyMTFlYjMyNjJmN2M3YTAyZTVmN2YyOWE0MDEwMzJmNGUyOGNmZGZhMyIsImV4cCI6MTcxMDA5MDEwN30.GC1QdG2n6ua_tV14LvjwqfCJG2daR89prlimeHj7Jew







#jwt here
        coreaddr: "http://127.0.0.1:2021"
    
    remote_participant_id: 03f73fbc5839491eee03578daff0cc34f6683601aae3cc57f4ad222fc2fc833ff3 #id here
    remote_participant_flow_queue: mockname #queue name here for moment not using