flow:
  _target_: aiflows.ControllerExecutorFlowModule.ControllerExecutorFlow.instantiate_from_default_config
  max_rounds: 30

  ### Subflows specification
  subflows_config:
    Controller:
      _target_: aiflows.ControllerExecutorFlowModule.ControllerAtomicFlow.instantiate_from_default_config
      commands:
        wiki_search:
          description: "Performs a search on Wikipedia."
          input_args: [ "search_term" ]
        ddg_search:
          description: "Query the search engine DuckDuckGo."
          input_args: [ "query" ]
        finish:
          description: "Signal that the objective has been satisfied, and returns the answer to the user."
          input_args: [ "answer" ]

    Executor:
      _target_: flows.base_flows.BranchingFlow.instantiate_from_default_config
      subflows_config:
        wiki_search:
          _target_: aiflows.ControllerExecutorFlowModule.WikiSearchAtomicFlow.instantiate_from_default_config
        ddg_search:
          _target_: aiflows.LCToolFlowModule.LCToolFlow.instantiate_from_default_config
          backend:
            _target_: langchain.tools.DuckDuckGoSearchRun