
flow:
    _target_: flow_modules.aiflows.ChatFlowModule.ChatAtomicFlow.instantiate_from_default_config
    name: "ChatFlowServer"
    description: "A flow that answers questions remotely."
    colink_info:
        cl:
            _target_: colink.CoLink
            jwt: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwcml2aWxlZ2UiOiJ1c2VyIiwidXNlcl9pZCI6IjAzZDI2MjRkMjI0YzcyODEzMWE3NDMyYjE2MWM3YjdkNWRkZTA1MTAyYmU3ODVmN2U0NTU4MTgzYjI0NDY0ODEwNiIsImV4cCI6MTcxMDA3ODQ1N30.F6R8kTepsXujDH8suKcUXyQhxNgnIKalETvYJKGCIhg




#jwt here
            coreaddr: http://127.0.0.1:2021

        load_incoming_states: True
    backend:
        api_infos: ???

    init_human_message_prompt_template: null